version: '3.6'
services: 
    application: 
        build:
            context: '.'
            dockerfile: Dockerfile
        container_name: dart
        ports: 
            - 4000:4000
        volumes:
            - "./:/app"
        working_dir: /app
        stdin_open: true
        tty: true